// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvPZsPcXJkNuntKIGiL6YxAp8jVppTWrM',
    appId: '1:949773776518:web:39a90daaa45fa42f6f0307',
    messagingSenderId: '949773776518',
    projectId: 'em-tech-c4ee3',
    authDomain: 'em-tech-c4ee3.firebaseapp.com',
    storageBucket: 'em-tech-c4ee3.appspot.com',
    measurementId: 'G-QEGPSH2452',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzDLhFDMeEyIjQc1iV79coaaxaZoowMLM',
    appId: '1:949773776518:android:7f259bcbf46197586f0307',
    messagingSenderId: '949773776518',
    projectId: 'em-tech-c4ee3',
    storageBucket: 'em-tech-c4ee3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADKp8GFU054qqNeujr5d7ppXD791uLhLQ',
    appId: '1:949773776518:ios:442aa2beea1a7c476f0307',
    messagingSenderId: '949773776518',
    projectId: 'em-tech-c4ee3',
    storageBucket: 'em-tech-c4ee3.appspot.com',
    iosBundleId: 'com.example.emtechProject',
  );
}
